version: '3.4'
services:
  weaviate:
    container_name: weaviate_db
    restart: on-failure:0
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.1
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
      DISK_USE_WARNING_PERCENTAGE: '80'

    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./weaviate_data:/var/lib/weaviate

  t2v-transformers:
    image: ${WEAVIATE_EMBEDDING_IMAGE}
    environment:
      ENABLE_CUDA: 0
