from abc import ABC, abstractmethod
from langchain_core.language_models.base import LanguageModelInput


class LLMInterface(ABC):
    @abstractmethod
    def generate_response(self, messages: LanguageModelInput) -> str:
        """Generate a response from the LLM for the given list of messages.

        Parameters:
            messages (LanguageModelInput): The list of messages to generate a response for.

        Returns:
            str: The response generated by the LLM.

        Examples:
            >>> llm = OpenAIModel()
            >>> messages = [('human', 'Olá, como vai?')]
            >>> response = llm.generate_response(messages)
            >>> print(response)
            "Olá, estou bem, obrigado. Como posso ajudar?"
        """
        raise NotImplementedError
